sl/check-property.sh --propertyfile: now a mandatory option

diff --git a/sl/check-property.sh.in b/sl/check-property.sh.in
--- a/sl/check-property.sh.in
+++ b/sl/check-property.sh.in
@@ -61,18 +61,15 @@ export MSG_FREE_NONPOINTER=': error: free() called on non-pointer value'
 #"caught signal " - not
 
 usage() {
-    printf "Usage: %s [--task TASK] [--trace FILE] -- path/to/test-case.c \
+    printf "Usage: %s --propertyfile FILE [--trace FILE] -- path/to/test-case.c \
 [-m32|-m64] [CFLAGS]\n\n" "$SELF" >&2
     cat >&2 << EOF
 
-    -t, --task TASK
-          A verification task. Currently supported tasks:
+    -p, --propertyfile FILE
+          A file specifying the verification property.  See the competition
+          rules for details: http://sv-comp.sosy-lab.org/2014/rules.php
 
-          'label'   : checks if an error label is reachable
-          'memory'  : checks if three memory properties defined in SVCOMP'13
-                      MemSafety category rules hold.
-
-    -e, --trace FILE
+    -t, --trace FILE
           A file name to write the trace to.
 
     -v, --verbose
@@ -89,20 +86,16 @@ usage() {
     For memory safety category, the FALSE result is further clarified as
     FALSE(p) where p is the property for which the Predator judges the
     program to be unsatisfactory.
-
-    If the verification property is not specified by the --task option, it is
-    assumed to be specified either in a file with the name "path/filename.prp"
-    or in a file "ALL.prp" in directory "path/" for a program "path/filename" 
 EOF
     exit 1
 }
 
-TASK=
+PRP_FILE=
 
 # write trace to stderr by default
 TRACE="/dev/fd/2"
 
-ARGS=$(getopt -o e:t:v -l "trace:,task:,verbose" -n "$SELF" -- "$@")
+ARGS=$(getopt -o p:t:v -l "propertyfile:,trace:,verbose" -n "$SELF" -- "$@")
 if test $? -ne 0; then
   usage; exit 1;
 fi
@@ -111,10 +104,10 @@ eval set -- $ARGS
 
 while true; do
   case "$1" in
-    -e|--trace)
+    -p|--propertyfile)
+      PRP_FILE="$2"; shift 2;;
+    -t|--trace)
       TRACE="$2"; shift 2;;
-    -t|--task)
-      export TASK="$2"; shift 2;;
     -v|--verbose)
       export VERBOSE="yes"; shift;;
     --)
@@ -123,31 +116,18 @@ while true; do
 done
 
 test -r "$1" || usage
+test -r "$PRP_FILE" || usage
 
-# load the property to be verified (if not specified explicitly)
-if test -z "$TASK"; then
-    PRP_FILE="${1}.prp"
-    test -r "$PRP_FILE" || PRP_FILE="$(dirname "${1}")/ALL.prp"
-    if test -r "$PRP_FILE"; then
-        if grep "ERROR" "$PRP_FILE" >/dev/null; then
-            TASK="label"
-        elif grep "valid-memtrack" "$PRP_FILE" >/dev/null; then
-            TASK="memory"
-        else
-            printf "%s: error: failed to classify verification property: %s\n" \
-                "$SELF" "$PRP_FILE" >&2
-            exit 1
-        fi
-    fi
+# classify the property to be verified
+if grep "label(ERROR)" "$PRP_FILE" >/dev/null; then
+    TASK="label"
+elif grep "valid-memtrack" "$PRP_FILE" >/dev/null; then
+    TASK="memory"
+else
+    printf "%s: error: failed to classify the property to verify: %s\n" \
+        "$SELF" "$PRP_FILE" >&2
+    exit 1
 fi
-
-case "$TASK" in
-    label|memory)
-        ;;
-    *)
-        printf "%s: error: verification propery not specified\n" "$SELF" >&2
-        exit 1
-esac
 
 # include common code base
 topdir="`dirname "$(readlink -f "$SELF")"`/.."
