sl/slgcc: colorize the output
... and split the output of bare gcc and the output of Predator.

diff --git a/sl/slgcc b/sl/slgcc
--- a/sl/slgcc
+++ b/sl/slgcc
@@ -1,4 +1,13 @@
 #!/bin/bash
+SELF="$0"
+
+die() {
+    printf "%s: %s\n" "$SELF" "$*"
+    exit 1
+}
+
+tty >/dev/null || die "standard input not a terminal"
+
 if test -z "$1" || test ! -e "$1"; then
     echo Usage: $0 foo.c
     exit 1
@@ -23,9 +32,6 @@ test -x "$SL_PLUG" \
 # use verbose level 0 by default
 test -z "$SL_VERBOSE" && SL_VERBOSE=0
 
-# use pp code listener by default
-#test -z "$SL_OPTS" && SL_OPTS="-fplugin-arg-libsl-dump-pp"
-
 # use chromium as default SVG_VIEWER
 test -z "$SVG_VIEWER" && SVG_VIEWER=chromium
 
@@ -35,14 +41,51 @@ if test x1 = "x$SL_PLOT"; then
 fi
 
 # run the gcc
-"$GCC" -c "$1" -o /dev/null -O0 -m32 \
-    -DPREDATOR \
-    -I../cl -I../cl/gcc -I../include -I../include/gcc \
-    -fplugin="$SL_PLUG" \
-    -fplugin-arg-libsl-verbose="$SL_VERBOSE" \
-    $SL_OPTS
+run_gcc() {
+    printf "Trying to compile \033[1;37m%s\033[0m ... " "$*" >/dev/tty
+    tmp="$(mktemp)"
+    test -w "$tmp" || die "mktemp failed"
+    trap "rm -f '$tmp'" RETURN
 
-RV=$?
+    if "$GCC" -o /dev/null -O0 -m32 -DPREDATOR                      \
+        -I../cl -I../cl/gcc -I../include -I../include/gcc -c "$@"   \
+        > "$tmp" 2>&1
+    then
+        printf "\033[1;32mOK\033[0m\n" >/dev/tty
+        cat "$tmp" >/dev/tty
+        printf "Running \033[1;34mPredator\033[0m ...\n" >/dev/tty
+    else
+        printf "\033[1;31mFAILED\033[0m\n\n" >/dev/tty
+        cat "$tmp"
+        return 1
+    fi
+
+    "$GCC" -o /dev/null -O0 -m32 -DPREDATOR                         \
+        -I../cl -I../cl/gcc -I../include -I../include/gcc           \
+        -fplugin="$SL_PLUG"                                         \
+        -fplugin-arg-libsl-verbose="$SL_VERBOSE" $SL_OPTS -c "$@"   \
+        2>&1 | grep ' \[-fplugin-libsl\]$'
+}
+
+# colorize the output
+run_gcc "$@" | sed -re 's| \[-fplugin-libsl\]$||'                              \
+        -e 's|(^.*) \[internal location\]$|\o033[1;30m\1\o033[0m|'             \
+        -e 's|(: error:) (.*)$|\1 \o033[1;31m\2\o033[0m|'                      \
+        -e 's|(: warning:) (.*)$|\1 \o033[1;33m\2\o033[0m|'                    \
+        -e 's|(: note:) (.*)$|\1 \o033[1;32m\2\o033[0m|'                       \
+        -e 's|(current memory usage:) ([0-9]+ MB)|\1 \o033[1;34m\2\o033[0m|'   \
+        -e 's|(!!! executing insn #[0-9]+ ...) (.*)$|\1 \o033[1;32m\2\o033[0m|'\
+        -e 's|took ([0-9.]+ s)|took \o033[1;34m\1\o033[0m|'                    \
+        -e 's/(: debug: *) ([<>]J[<>]|AAA)/\1 \o033[1;31m\2\o033[0m/'          \
+        -e 's/(: debug: SymHeap::)(objSetConcrete)/\1\o033[1;33m\2\o033[0m/'   \
+        -e 's/(: debug:) (spliceOutListSegment)/\1 \o033[1;34m\2\o033[0m/'     \
+        -e 's/(: debug:) (<<<|>>>)/\1 \o033[1;34m\2\o033[0m/'                  \
+        -e 's/(: debug:) ___ (entering|we are)/\1 \o033[1;32m___\o033[0m \2/'  \
+        &
+
+# FIXME: this kills _all_ the cc1 processes we are permitted to kill !!!
+trap "killall --wait cc1" SIGINT
+wait
 
 if test x1 = "x$SL_PLOT"; then
     # visualize graphs
@@ -52,5 +95,3 @@ if test x1 = "x$SL_PLOT"; then
     printf "done\n"
     "$SVG_VIEWER" *.svg
 fi
-
-exit $RV
