maint: hard-code absolute paths for GCC_HOST and SL_PLUG
... in chk-error-label-reachability.sh and sl/slgcc when we are out
of a git repository.

diff --git a/sl/slgcc b/sl/slgcc
--- a/sl/slgcc
+++ b/sl/slgcc
@@ -14,21 +14,14 @@ if test -z "$1" || test ! -e "$1"; then
     exit 1
 fi
 
-self="`readlink -f "$0"`"
-topdir="`dirname "$self"`/.."
-
 # basic setup
-SL_BUILD="$topdir/sl_build"
-SL_PLUG="$SL_BUILD/libsl.so"
-GCC="$topdir/gcc-install/bin/gcc"
+topdir="`dirname "$(readlink -f "$SELF")"`/.."
+export SL_PLUG="$topdir/sl_build/libsl.so"
+export GCC_HOST="$topdir/gcc-install/bin/gcc"
 
 # initial checks
-test -x "$GCC" || exit 1
-
-# attempt to make
-test -x "$SL_PLUG" \
-    || make -s $MAKEOPTS -C "$topdir/sl" \
-    || exit 1
+test -x "$GCC_HOST" || die "host GCC not found: ${GCC_HOST}"
+test -r "$SL_PLUG"  || die "Predator GCC plug-in not found: ${SL_PLUG}"
 
 # use chromium as default SVG_VIEWER
 test -z "$SVG_VIEWER" && SVG_VIEWER=chromium
@@ -62,7 +55,7 @@ run_gcc() {
     test -w "$tmp" || die "mktemp failed"
     trap "rm -f '$tmp'" RETURN
 
-    if "$GCC" -o /dev/null -O0 -m32 -DPREDATOR                      \
+    if "$GCC_HOST" -o /dev/null -O0 -m32 -DPREDATOR                 \
         -I../cl -I../cl/gcc -I../include -I../include/gcc -c "$@"   \
         > "$tmp" 2>&1
     then
@@ -75,7 +68,7 @@ run_gcc() {
         return 1
     fi
 
-    "$GCC" -o /dev/null -O0 -m32 -DPREDATOR                         \
+    "$GCC_HOST" -o /dev/null -O0 -m32 -DPREDATOR                    \
         -I../cl -I../cl/gcc -I../include -I../include/gcc           \
         -fplugin="$SL_PLUG" -fplugin-arg-libsl-pid-file="$pidfile"  \
         -fplugin-arg-libsl-args=error_label:ERROR $SL_OPTS -c "$@"  \
