sl/slgcc: add error message if Predator fails

diff --git a/sl/slgcc b/sl/slgcc
--- a/sl/slgcc
+++ b/sl/slgcc
@@ -84,6 +84,9 @@ run_gcc() {
         -fplugin-arg-libsl-args=error_label:ERROR $SL_OPTS "$@"     \
         2>&1 | stdbuf --output=L grep -E                            \
         ' \[-fplugin=libsl\.so\]$|CL_BREAK_IF|INT3|SIGTRAP|internal compiler error|undefined symbol'
+    if [ $? -ne 0 ]; then
+        printf "\033[1;31mFAILED\033[0m\n" >&2
+    fi
 }
 
 forward_signal() {
