sl: make slgcc use GCC_HOST set from cmake
slgcc is now generated from slgcc.in using the GCC_HOST as set when the
cmake was run.

diff --git a/sl/slgcc.in b/sl/slgcc.in
--- a/sl/slgcc.in
+++ b/sl/slgcc.in
@@ -30,11 +30,16 @@ seek_input_file "$@" || usage
 topdir="`dirname "$(readlink -f "$SELF")"`/.."
 export SINK="/dev/null"
 export SL_PLUG="$topdir/sl_build/libsl.so"
-export GCC_HOST="$topdir/gcc-install/bin/gcc"
+export GCC_HOST='@GCC_HOST@'
 export GCC_OPTS="-S -o $SINK -O0 -I$topdir/include/predator-builtins -DPREDATOR"
 
 # initial checks
-"$GCC_HOST" --version >"$SINK" || die "unable to run gcc: $GCC_HOST --version"
+"$GCC_HOST" --version >"$SINK" 2>&1 || {
+    GCC_HOST="$topdir/gcc-install/bin/gcc"
+    "$GCC_HOST" --version >"$SINK" \
+        || die "unable to run gcc: $GCC_HOST --version"
+}
+
 test -r "$SL_PLUG"  || die "Predator GCC plug-in not found: ${SL_PLUG}"
 
 # use chromium as default SVG_VIEWER
