slgcc: colorize the output only if writing to a tty

diff --git a/sl/slgcc b/sl/slgcc
--- a/sl/slgcc
+++ b/sl/slgcc
@@ -9,8 +9,6 @@ die() {
     exit 1
 }
 
-tty >/dev/null || die "standard input not a terminal"
-
 if test -z "$1" || test ! -e "$1"; then
     echo Usage: $0 foo.c
     exit 1
@@ -45,9 +43,21 @@ test -w "$pidfile" || die "mktemp failed"
 export pidfile
 trap "rm -f '$pidfile'" EXIT
 
+# check whether stdout is connected to a terminal
+if tty 0>&1 >/dev/null; then
+    # initialize coloring escape sequences
+    export S='\o033[1;30m'
+    export R='\o033[1;31m'
+    export G='\o033[1;32m'
+    export Y='\o033[1;33m'
+    export B='\o033[1;34m'
+    export W='\o033[1;37m'
+    export N='\o033[0m'
+fi
+
 # run the gcc
 run_gcc() {
-    printf "Trying to compile \033[1;37m%s\033[0m ... " "$*" >/dev/tty
+    printf "Trying to compile \033[1;37m%s\033[0m ... " "$*" >&2
     tmp="$(mktemp)"
     test -w "$tmp" || die "mktemp failed"
     trap "rm -f '$tmp'" RETURN
@@ -56,11 +66,11 @@ run_gcc() {
         -I../cl -I../cl/gcc -I../include -I../include/gcc -c "$@"   \
         > "$tmp" 2>&1
     then
-        printf "\033[1;32mOK\033[0m\n" >/dev/tty
-        cat "$tmp" >/dev/tty
-        printf "Running \033[1;34mPredator\033[0m ...\n" >/dev/tty
+        printf "\033[1;32mOK\033[0m\n" >&2
+        cat "$tmp" >&2
+        printf "Running \033[1;34mPredator\033[0m ...\n" >&2
     else
-        printf "\033[1;31mFAILED\033[0m\n\n" >/dev/tty
+        printf "\033[1;31mFAILED\033[0m\n\n" >&2
         cat "$tmp"
         return 1
     fi
@@ -82,30 +92,30 @@ forward_signal() {
 
 # colorize the output
 run_gcc "$@" | stdbuf --output=L sed -re 's| \[-fplugin-libsl\]$||'            \
-        -e 's|(^.*) \[internal location\]$|\o033[1;30m\1\o033[0m|'             \
-        -e 's|(: error:) (.*)$|\1 \o033[1;31m\2\o033[0m|'                      \
-        -e 's|(: warning:) (.*)$|\1 \o033[1;33m\2\o033[0m|'                    \
-        -e 's|(: note:) (.*)$|\1 \o033[1;32m\2\o033[0m|'                       \
-        -e 's|(current memory usage: *) ([0-9.]+ MB)|\1 \o033[1;34m\2\o033[0m|'\
-        -e 's|(peak memory usage: *) ([0-9.]+ MB)|\1 \o033[1;31m\2\o033[0m|'   \
-        -e 's|(!!! executing insn #[0-9]+ ...) (.*)$|\1 \o033[1;32m\2\o033[0m|'\
-        -e 's|(variable[:]? #[0-9]+:)([a-zA-Z0-9_.]+)|\1\o033[1;32m\2\o033[0m|'\
-        -e 's|(per target) (L[0-9]+)|\1 \o033[1;32m\2\o033[0m|'                \
-        -e 's|(initial size of state was) ([0-9]+)|\1 \o033[1;37m\2\o033[0m|'  \
-        -e 's|(#[0-9]+)|\o033[1;37m\1\o033[0m|'                                \
-        -e 's|(block L[0-9]+) (in progress)|\1 \o033[1;33m\2\o033[1;32m|'      \
-        -e 's|(... while executing) (.*\(\))|\1 \o033[1;33m\2\o033[0m|'        \
-        -e 's|took ([0-9.]+ s)|took \o033[1;31m\1\o033[0m|'                    \
-        -e 's|(internal compiler error:) (.*)$|\1 \o033[1;31m\2\o033[0m|'      \
-        -e 's|(undefined symbol:) (.*)$|\1 \o033[1;31m\2\o033[0m|'             \
-        -e 's/(CL_BREAK_IF|INT3|SIGTRAP)/\o033[1;31m\1\o033[0m/'               \
-        -e 's/(importGlVar\(\))/\o033[1;31m\1\o033[0m/'                        \
-        -e 's/(: debug: *) ([<>]J[<>]|AAA)/\1 \o033[1;31m\2\o033[0m/'          \
-        -e 's/(: debug: SymHeap::)(objSetConcrete)/\1\o033[1;33m\2\o033[0m/'   \
-        -e 's/(: debug:) \(x\) (.*)$/\1 \o033[1;33m(x)\o033[0m \2/'            \
-        -e 's/(: debug:) (spliceOutListSegment)/\1 \o033[1;34m\2\o033[0m/'     \
-        -e 's/(: debug:) (<<<|>>>)/\1 \o033[1;34m\2\o033[0m/'                  \
-        -e 's/(: debug:) ___ (entering|we are)/\1 \o033[1;32m___\o033[0m \2/'  \
+        -e "s|(^.*) \[internal location\]\$|$S\1$N|"                           \
+        -e "s|(: error:) (.*)\$|\1 $R\2$N|"                                    \
+        -e "s|(: warning:) (.*)\$|\1 $Y\2$N|"                                  \
+        -e "s|(: note:) (.*)\$|\1 $G\2$N|"                                     \
+        -e "s|(current memory usage: *) ([0-9.]+ MB)|\1 $B\2$N|"               \
+        -e "s|(peak memory usage: *) ([0-9.]+ MB)|\1 $R\2$N|"                  \
+        -e "s|(!!! executing insn #[0-9]+ ...) (.*)\$|\1 $G\2$N|"              \
+        -e "s|(variable[:]? #[0-9]+:)([a-zA-Z0-9_.]+)|\1$G\2$N|"               \
+        -e "s|(per target) (L[0-9]+)|\1 $G\2$N|"                               \
+        -e "s|(initial size of state was) ([0-9]+)|\1 $W\2$N|"                 \
+        -e "s|(#[0-9]+)|$W\1$N|"                                               \
+        -e "s|(block L[0-9]+) (in progress)|\1 $Y\2$G|"                        \
+        -e "s|(... while executing) (.*\\(\\))|\1 $Y\2$N|"                     \
+        -e "s|took ([0-9.]+ s)|took $R\1$N|"                                   \
+        -e "s|(internal compiler error:) (.*)\$|\1 $R\2$N|"                    \
+        -e "s|(undefined symbol:) (.*)\$|\1 $R\2$N|"                           \
+        -e "s/(CL_BREAK_IF|INT3|SIGTRAP)/$R\1$N/"                              \
+        -e "s/(importGlVar\\(\\))/$R\1$N/"                                     \
+        -e "s/(: debug: *) ([<>]J[<>]|AAA)/\1 $R\2$N/"                         \
+        -e "s/(: debug: SymHeap::)(objSetConcrete)/\1$Y\2$N/"                  \
+        -e "s/(: debug:) \\(x\\) (.*)\$/\1 $Y(x)$N \2/"                        \
+        -e "s/(: debug:) (spliceOutListSegment)/\1 $B\2$N/"                    \
+        -e "s/(: debug:) (<<<|>>>)/\1 $B\2$N/"                                 \
+        -e "s/(: debug:) ___ (entering|we are)/\1 $G___$N \2/"                 \
         &
 
 # redirect terminating signals to our plug-in
