sl/slgcc: print escape sequences only to terminals
Suggested-by: Petr Peringer

diff --git a/sl/slgcc.in b/sl/slgcc.in
--- a/sl/slgcc.in
+++ b/sl/slgcc.in
@@ -65,17 +65,17 @@ fi
 
 # run the gcc
 run_gcc() {
-    printf "Trying to compile \033[1;37m%s\033[0m ... " "$*" >&2
+    printf "Trying to compile ${W/o0/0}%s${N/o0/0} ... " "$*" >&2
     tmp="$(mktemp /tmp/slgcc.XXXXXX)"
     test -w "$tmp" || die "mktemp failed"
     trap "rm -f '$tmp'" RETURN
 
     if "$GCC_HOST" $GCC_OPTS "$@" > "$tmp" 2>&1; then
-        printf "\033[1;32mOK\033[0m\n" >&2
+        printf "${G/o0/0}OK${N/o0/0}\n" >&2
         cat "$tmp" >&2
-        printf "Running \033[1;34mPredator\033[0m ...\n" >&2
+        printf "Running ${B/o0/0}Predator${N/o0/0} ...\n" >&2
     else
-        printf "\033[1;31mFAILED\033[0m\n\n" >&2
+        printf "${R/o0/0}FAILED${N/o0/0}\n\n" >&2
         cat "$tmp"
         return 1
     fi
@@ -87,7 +87,7 @@ run_gcc() {
         3>&1 1>&2 2>&3 | stdbuf --output=L grep -E                  \
         ' \[-fplugin=libsl\.so\]$|CL_BREAK_IF|INT3|SIGTRAP|internal compiler error|undefined symbol'
     if [ $? -ne 0 ]; then
-        printf "\033[1;31mFAILED\033[0m\n" >&2
+        printf "${R/o0/0}FAILED${N/o0/0}\n" >&2
     fi
 }
 
